<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * The first product table RideMate has ever had.
 *
 * WHAT AN ACCOUNT IS, AND WHAT IT DELIBERATELY IS NOT
 *
 * An account is a credential identity: the phone number that proves who is
 * signing in, and whether they are allowed to. It is not a profile. Nothing
 * here is shown to another member — no name, no photo, no rating, no score.
 *
 * That separation is the reason this is not Laravel's `users` table, which was
 * deleted in Phase 8 for encoding an email-and-password model RideMate does not
 * use. A row that mixes credentials with public presentation forces every read
 * to filter columns by audience, and that is exactly how a phone number ends up
 * in a payload a stranger can see. A `profiles` table arrives when a real
 * name-capture flow exists to fill it.
 *
 * WHY THERE IS NO `verifications` TABLE FOR THIS
 *
 * An account comes into existence only after a passcode has been verified, so
 * a verifications table would hold one row per account, of one kind, in one
 * state, forever. That is a column.
 *
 * `phone_verified_at` is nevertheless kept distinct from `created_at`, because
 * they are different facts that merely coincide today. `created_at` is an
 * infrastructure timestamp; `phone_verified_at` is a domain claim. The day a
 * phone-change flow ships, a row where the two had been conflated would assert
 * that the current number was verified at signup, which would be false.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('accounts', function (Blueprint $table): void {
            // UUIDv7, generated by the application. Time-ordered so it does not
            // fragment the index the way v4 does, and known before INSERT so an
            // action can build the whole aggregate without a round-trip.
            $table->uuid('id')->primary();

            // E.164 only, never the member's formatting. `0532...`, `+90532...`
            // and `90532...` are one human; storing what was typed guarantees
            // three accounts for them. Normalization happens once, at the
            // request boundary, in App\Support\PhoneNumber.
            //
            // E.164 caps at 15 digits plus '+'. 20 leaves room without pretending
            // the column is free-text.
            $table->string('phone_e164', 20)->unique();

            $table->timestampTz('phone_verified_at');

            // Two states, because two states have behaviour. `active`
            // authenticates; `suspended` is refused at issuance, at refresh and
            // at every authenticated request. Deletion, deactivation and a
            // pending state are deferred until something produces or consumes
            // them — see docs/architecture.md.
            $table->string('status', 16)->default('active');

            $table->timestampsTz();
        });

        // Blueprint cannot express a check constraint, and the application
        // enum is not a database guarantee: a bad migration, a console command
        // or a manual UPDATE would all bypass it. The set is small and stable
        // enough that the database should refuse anything outside it.
        DB::statement(
            "alter table accounts add constraint accounts_status_check
             check (status in ('active', 'suspended'))"
        );
    }

    public function down(): void
    {
        Schema::dropIfExists('accounts');
    }
};
